### ISSUE TITLE
pypi installation: pygobject doesn't get installed as dependency, results in runtime error

### ISSUE THREAD

**Issue by seltzered** [johannesjh/favagtk#12] opened 2022-04-22 17:42 UTC
Installing fava-gtk via pypi (i.e. `pip install fava-gtk`) on python 3.10 results in a runtime error if the user hasn't already done `pip install PyGObject`. 

```
> fava-gtk 
Traceback (most recent call last):
  File "/home/me/.pyenv/versions/3.10.1/bin/fava-gtk", line 5, in <module>
    from fava_gtk.main import main
  File "/home/me/.pyenv/versions/3.10.1/lib/python3.10/site-packages/fava_gtk/__init__.py", line 4, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

I was about to submit a PR to fix this by just modifying requirements/main.in, but it just led to more questions after realizing you also have it already listed in sys.in. 

This is seemingly because the requirement PyGObject isn't listed in requirements/main.in , but it's worth noting that adding  (particularly on ubuntu) may also lead to an installation issue of: 

```
      Perhaps you should add the directory containing `gobject-introspection-1.0.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'gobject-introspection-1.0' found
      Command '('pkg-config', '--print-errors', '--exists', 'gobject-introspection-1.0 >= 1.56.0')' returned non-zero exit status 1.
      
      Try installing it with: 'sudo apt install libgirepository1.0-dev'
      [end of output]
```

fava-gtk does run fine after doing 'sudo apt install libgirepository1.0-dev' and installing with a main.in file (and pip-compile-multi ran afterward) with a line like `PyGObject>=3.42.1`

Environment: Ubuntu 21.10

**Comment by johannesjh** [comment] 2022-05-11 14:41
thank you, I can confirm that the PyGObject requirement is indeed missing in the python wheel, that's a bug. To be honest, I could really need some help or directions for how to package the app.

Past problems:

* python packaging was complicated: In this project, I first started using poetry, with a dependency on PyGObject. This worked fine on my machine, but @yagebu had problems with this setup because on his machine, PyGObject did not install using pip or poetry (and there was no way to instruct poetry to use system packages). That's why I started using pip-compile-multi, segmenting the requirements in system requirements vs main requirements.
* flatpak packaging was no fun either: I tried using [flatpak-builder-tools](https://github.com/flatpak/flatpak-builder-tools/), using both pip and poetry. This hashes all input files and creates reproducible build, very nice. But flatpak-builder-tools' output failed to install, I could not get it working properly. For this reason, the flatpak build currently uses an online installation.

Future plans: I am currently working on a GTK4 rewrite, and I am considering if I should omit python packaging. That's because I started using compiled gresources; these cannot be installed by python packages, as far as I know. For this reason, I might provide the app as flatpak build only, no more python wheels.

**Comment by seltzered** [comment] 2022-05-12 05:39
Got it. I'm new to gtk, and aware of the other discussion ( https://github.com/johannesjh/fava-gtk/issues/6 ) in how doing flatpak has some sandboxing complexity around extensions.

(Digression: Probably not everyone's cup of tea but another approach I've been exploring a prototype of is a fava+beancount app based off [Theia](https://theia-ide.org/) (i.e. vscode). Essentially curious what a cross-platform, enclosed 'app' with fava,  https://github.com/Lencerf/vscode-beancount , importer workflows could feel like and if it would help beancount+fava reach a wider community. Not much progress yet (may abandon to explore fava-gtk more) but will bring it up on the beancount mailing list once there's something worth sharing.)

**Comment by johannesjh** [comment] 2022-05-12 07:09
I pushed the GTK4 rewrite into a branch named [gtk4](https://github.com/johannesjh/fava-gtk/tree/gtk4). 

current state, things I like about it:
* it works on my machine :-), in other words, this code should still be considered a first, experimental version. testing + collaboration + improvements welcome.
* it should be very easy to start working on this app using GNOME Builder: clone the project in Builder and click run, it should all work automagically out of the box
* the flatpak build now works without network access and even succeeds in installing scikit-learn without network access, which is nice.
* the UI uses GTK4, and I used the awesome [blueprint](https://gitlab.gnome.org/jwestman/blueprint-compiler) language to write .ui files, this makes them so much easier to read and write!

things to improve:
* the flatpak build uses org.gnome.Platform//master because it includes webkit2gtk 5.0. Unfortunately, I could not get the build to work properly using org.gnome.Platform//42 which (when I tried a few weeks ago) did not include webkit2gtk 5.0
* package metadata such as appstream descriptions and screenshots
* CI workflow is missing
* flathub packaging is missing

...I maintain a `Todo.md` file with these todos.

**Comment by johannesjh** [comment] 2022-05-13 06:02
You motivated me to spend some more time with the favagtk app last night. The GTK4 branch now builds against a stable platform.

by "stable platform" I mean, I am now using `org.gnome.Platform//42` instead of `org.gnome.Platform//master`. In consequence the flatpak build must compile and install webkit2gtk-5 because this does not come included in platform 42. Current state of affairs:

* I got it working on my machine. 
* I added a github ci workflow
* but github ci kills the build because it takes too long. 

...I might try again on gnome's gitlab.

**Comment by johannesjh** [comment] 2022-06-19 07:51
I finished the migration to GTK4 and moved the project to gnome's gitlab infrastructure, see [favagtk's new project page over on gnome's gitlab](https://gitlab.gnome.org/johannesjh/favagtk). 

I'll close this ticket because I do not publish favagtk on pypi anymore. This means, favagtk cannot be directly invoked as a python script from the commandline anymore. Instead it is published as flatpak application. The reason being that the tools that I have started to use do not fit python packaging's approach, e.g.: the build process uses meson and resource files are compiled into resource bundles that must be installed in the user's system.

**Closed by johannesjh** 2022-06-19 07:51 UTC
